---
#CodeBook
###author: Julie Foster
###date: September 4, 2016
---


## Instructions for project:  
The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 1) a tidy data set as described below, 2) a link to a Github repository with your script for performing the analysis, and 3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your available at the site where the data was obtained:  
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones  
Here are the data for the project:  
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip  
You should create one R script called run_analysis.R that does the following.  
1.	Merges the training and the test sets to create one data set.
2.	Extracts only the measurements on the mean and standard deviation for each measurement.
3.	Uses descriptive activity names to name the activities in the data set
4.	Appropriately labels the data set with descriptive variable names.
5.	From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

##Data Overview
Human Activity Recognition database built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.  
Data Set Characteristics: Multivariate  
Number of Instances: 10299  
Number of Attributes: 561  

##Data Collection
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years ("subject")  
Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist ("activity")  
Using its embedded accelerometer and gyroscope, 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz was captured  
The experiments have been video-recorded to label the data manually  
The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.  
Test and training datasets can be found under the respective sub directories named "test" and "train"  
Unit of Measurement: The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz.  

##Raw Dataset
The raw dataset is downloaded from the UCI Machine Learning Repository as a zipped directory.  The files from the raw dataset that are being used in this project are:
Subject Files
*	test/subject_test.txt
*	train/subject_train.txt
Activity Files
*	test/X_test.txt
*	train/X_train.txt
Data Files
*	test/y_test.txt
*	train/y_train.txt

* features.txt - Names of column variables in the data files.
* activity_labels.txt - Names of the activity labels in the activity files.


##The run_analysis.R script:

Step 1:   Merge the training and the test sets to create one data set:  "largeData"
*	Download and uncompress the raw data zip directory
*       Read in test datasets, renaming the column labels, cbind three tables into "testData".
*	Read in train datasets, renaming the column labels, cbind three tables into "trainData".
*	Merge "testData" and "trainData", creating "largeData".  
> dim(largeData)  
[1] 10299   563  

Step 2:   Extract the measurements on the mean and standard deviation for each measurement.  
*	Extract mean measurements into "meanData".  
*	Extract std measurements into "stdData".
*	Merge "largeData$subject", "largeData$activity", "meanData" and "stdData", creating "meanstdData".  
> dim(meanData)  
[1] 10299    46  
> dim(stdData)  
[1] 10299    33  
> dim(meanstdData)  
[1] 10299    79  

Step 3:  Use descriptive activity names to name the activities in the data set.  (Folded into Step 1,  above).

Step 4:  Appropriately label the dataset with descriptive variable names.

*   rename columns from "largeData"
*	remove () from activity column names

Step 5:  From this dataset, create a second, independent tidy dataset with the average of each variable for each activity and each subject.

*	Average by subject for each variable and rename column names  
> dim(by_subj)  
[1] 77 30  
*	Average by activity for each variable  
> dim(by_act)  
[1] 77  6  
*	Merge by_act and by_subj to create new "avg_dataset"  
> dim(avg_dataset)  
[1] 77 36  
*	Write "avg_dataset" to output file, "avg_dataset.txt".

